version: '3.2'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_DATABASE: spaces
    ports: 
    - 33060:3306
    volumes:
    - type: "bind"
      source: ./sql
      target: /docker-entrypoint-initdb.d/

  spaces:
    build: .
    depends_on:
    - db
    ports:
    - 8080:8080
    volumes:
    - type: "bind"
      source: .
      target: /opt/spaces
    working_dir: /opt/spaces
    user: $UID
    command: "sbt ~reStart"
